project_hello:
    defaults: { _controller: ProjectBundle:Default:index }
    pattern: "/"

project_all_posts:
    defaults: { _controller: ProjectBundle:Default:index }
    pattern: "/posts"




project_new_post:
    defaults: { _controller: ProjectBundle:Default:newPost }
    pattern: "/new_post"

project_submit_post:
    defaults: { _controller: ProjectBundle:Default:submitPost }
    pattern: "/submit_post"

project_get_post:
    defaults: { _controller: ProjectBundle:Default:post }
    pattern: "/post/{id}"

project_edit_post:
    defaults: { _controller: ProjectBundle:Default:editPost }
    pattern: "/edit/{id}"

project_delete_post:
    defaults: { _controller: ProjectBundle:Default:deletePost }
    pattern: "/delete/{id}"

project_submit_post:
    defaults: { _controller: ProjectBundle:Default:submitPost }
    pattern: "/submit_post"

project_edit_posts:
    defaults: { _controller: ProjectBundle:Default:viewAll }
    pattern: "/view_all"

project_submit_comment:
    defaults: { _controller: ProjectBundle:Default:submitComment }
    pattern: "/submit_comment"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal